
find_program(CMAKE_C_COMPILER   clang REQUIRED)
find_program(CMAKE_CXX_COMPILER clang++ REQUIRED)

# MAYBE TEST BY MANUALLY SETTING THE EMSCRIPTEN COMPILER
# set(CMAKE_C_COMPILER   )
# set(CMAKE_CXX_COMPILER )

set(CMAKE_C_COMPILER_ID Clang)
set(CMAKE_CXX_COMPILER_ID Clang)

set(CMAKE_C_FLAGS_INIT "${CMAKE_C_FLAGS_INIT}")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_CXX_FLAGS_INIT}")
